### ISSUE TITLE
Home Screen

### ISSUE THREAD

**Issue by slamdslam** [JuiMin/HALP#66]
Refer to notes for build:

https://docs.google.com/document/d/1HBv1MCxfPQZROFvANMPLLxZhLjra6MDwa0HySJ2sKO8/edit

**Comment by dlee20013** [comment]
PRIMARY WORK:

- [ ] App Icon
- [ ] Sort Newest/Trending
- [ ] Card Contents - Boards/Posts 
- [ ] Upvotes - Left bottom of card has likes and dislikes w/ comment count
- [ ] Dango menu post/board for flagging/sharing(maybe url)/moderate if its your post
- [ ] Empty page if there are no subscriptions

Secondary:

- Settings for view modes (card mode/compact mode/photo grid)
- Drop-down
- Gestures pull down for menus
